parameters:
#    fer_user.example.class: Fer\UserBundle\Example

services:
#    fer_user.example:
#        class: %fer_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
  my.facebook.user:
      class: Fer\UserBundle\Security\User\Provider\FacebookProvider
      arguments:
          facebook: "@fos_facebook.api"
          userManager: "@fos_user.user_manager"
          validator: "@validator"
          container: "@service_container"
