parameters:
#    fer_user.example.class: Fer\UserBundle\Example

services:
#    fer_user.example:
#        class: %fer_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
