jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chainprovider:
          chain:
              providers: [my_fos_facebook_provider, fos_userbundle]
        fos_userbundle:
          id: fos_user.user_provider.username
        my_fos_facebook_provider:
          id: my.facebook.user

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false
        api:
            pattern:    ^/api/oauth
            fos_oauth:  true
            stateless:  true
        secured_area:
            pattern:    ^/api/basic
            anonymous: ~
            http_basic:
                realm: "Demo Http basic"
        wsse_secured:
            pattern:   ^/api/wsse
            stateless:    true
            provider: fos_userbundle
            wsse:      { nonce_dir: null, lifetime: 3000, realm: "Demo API", profile: UsernameToken }
        main:
            pattern:    ^/
#            fos_facebook:
#                app_url: "http://apps.facebook.com/appName/"
#                server_url: "http://localhost/facebookApp/"
#                provider: my_fos_facebook_provider
#                login_path: fos_user_security_login
#                check_path: /facebook/login_check
#                check_path: fos_facebook_security_check
#                default_target_path: /
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:       true
            anonymous:    true


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/libre, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/basic, roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: ^/api/oauth, roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: ^/oauth/v2/auth, roles: [ IS_AUTHENTICATED_FULLY ] }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
